approvedGitRepositories:
  - "https://github.com/yarnpkg/*"
  - "ssh://git@github.com/yarnpkg/*"

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 7d

npmPreapprovedPackages:
  - "@dtelecom/secure-chat-client"
  - "@dtelecom/vodozemac-wasm"
